---
title: ""
---
	graph LR
	
	R((("用户文件夹 \n Rime/")))
	
	R --o 输入方案{{"[具体输入方案] 相关"}}
	R --o 插件{{"[Lua插件] 相关"}}
	R --o 部署{{"[部署] 与 [使用时动态生成] 相关"}}
	R --o 核心与前端{{"[Rime引擎默认配置] 与 [前端配置] 相关"}}
	
	输入方案 --- a1["方案配置文件 \n( *.schema.yaml )"]
	输入方案 --- a2["固态词典/码表文件 \n( *.dict.yaml )"]
	输入方案 --- a3["自定义短语/免编译型词库文件 \n( 常见: custom_phrase.txt )"]
	输入方案 --- a4["其他可用于引用的配置文件 \n( *.yaml )"]
	输入方案 --- a5["引擎会解析的\n对配置文件( *.yaml )\n再自定义的配置文件 \n( *.custom.yaml )"]
	输入方案 --- a6["方案的固态词典( *.dict.yaml )于部署时\n可默认导入的“八股文”词频表 \n( essay.txt )"]
	输入方案 --- a7["librime“八股文”语法插件的模型文件 \n( *.gram )"]
	输入方案 --- a8["librime联想词插件的数据文件 \n( 常见: predict.db )"]
	
	插件 --- b1["独立的Lua插件 \n( lua/*.lua )"]
	插件 --- b2["位于 rime.lua 中的函数对象"]
	插件 --- b3["插件依赖的库，\n所需的配置、数据等"]
	
	部署 --o c1(["部署产物存放文件夹 \n( build/ )"])
	部署 --o c2(["用户动态词典文件夹 \n( *.userdb/ )"])
	
	核心与前端 --- d1["引擎整体默认配置 及 对应的再自定义文件  \n( default.yaml、default.custom.yaml )"]
	核心与前端 --- d2["用户引擎状态历史记录  \n( user.yaml )"]
	核心与前端 --- d3["发行版安装信息 \n( installation.yaml )"]
	
	R ---o d4[["其它前端相关部分 和 用户自行创建内容……"]]